# Generated by Django 4.2.3 on 2023-07-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='issue_number',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='publisher',
        ),
        migrations.AddField(
            model_name='comic',
            name='desc',
            field=models.TextField(default='NULL'),
        ),
    ]
